# Generated by Django 5.1.6 on 2025-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('transgender', 'Transgender'), ('undisclosed', 'Undisclosed'), ('other', 'Other')], max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('customer', 'Customer'), ('system_admin', 'System Administrator'), ('support', 'Support Staff'), ('finance', 'Finance Staff')], default='customer', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('deleted', 'Deleted'), ('pending_verification', 'Pending Verification')], default='inactive', max_length=20, verbose_name='status'),
        ),
    ]
