# Generated by Django 5.1.6 on 2025-04-03 12:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('file', models.FileField(upload_to='management_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'dcm'])])),
                ('document_type', models.CharField(choices=[('Water Treatment Plan', 'Water Treatment Plan'), ('Water Quality Report', 'Water Quality Report'), ('Water Quality Monitoring', 'Water Quality Monitoring'), ('Water Quality Assessment', 'Water Quality Assessment'), ('Water Quality Regulations', 'Water Quality Regulations')], max_length=50)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('access_audit', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Management Document',
                'verbose_name_plural': 'Management Documents',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='management__content_13cbd0_idx')],
            },
        ),
    ]
