# Generated by Django 5.2 on 2025-04-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterguideline',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the guideline.', null=True),
        ),
        migrations.AddField(
            model_name='waterguideline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=255),
        ),
    ]
