# Generated by Django 5.1.6 on 2025-05-19 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='handlers',
            field=models.ManyToManyField(blank=True, related_name='staffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managementattachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='waterguidelineparameter',
            name='guideline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='management.waterguideline'),
        ),
        migrations.AddField(
            model_name='waterlabreport',
            name='customer_request',
            field=models.ForeignKey(help_text='Associated customer request that initiated the lab report.', on_delete=django.db.models.deletion.CASCADE, related_name='water_lab_reports', to='management.customerrequest'),
        ),
        migrations.AddField(
            model_name='waterlabparameter',
            name='lab_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='management.waterlabreport'),
        ),
        migrations.AddField(
            model_name='waterreportattachment',
            name='customer_request',
            field=models.ForeignKey(help_text='Associated customer request that initiated the lab report.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='management.customerrequest'),
        ),
        migrations.AddField(
            model_name='waterreportattachment',
            name='water_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='management.waterlabreport'),
        ),
        migrations.AddIndex(
            model_name='managementattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='management__content_13cbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='waterreportattachment',
            index=models.Index(fields=['customer_request', 'water_report'], name='management__custome_0858fa_idx'),
        ),
    ]
