# Generated by Django 5.2 on 2025-04-16 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_waterguideline_description_waterguideline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterreportattachment',
            name='water_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='management.waterlabreport'),
        ),
    ]
